export const API_BASE_URL = "http://localhost:5005";

//export const fabricTypes = ['Cotton', 'Muslin', 'Silk', 'Endi Muslin', 'Mixed Muslin (Muslin & Endi)', 'Soft Silk', 'Half Silk (Silk & Cotton)', 'Endi Silk', 'Mixed Silk (Silk & Cotton)', 'Dupion Silk', 'Katan', 'Mixed Cotton', 'Jamdani Half Silk (Silk & Cotton)', 'Viscott (Viscose & Cotton)', 'Viscose', 'Voile', 'Vortex-Cotton', 'Handloom Cotton', 'Jacquard Viscose', 'Vortex Cotton', 'Mixed Viscose', 'Cottray (Cotton & Rayon)', 'Handloom Viscose', 'Ramie Cotton', 'Mixed Silk', 'Joysree Silk', 'Blended Muslin (Muslin & Silk)', 'Mixed Muslin', 'Endi Silk-Muslin', 'Linen', 'Satin', 'SICO (Silk & Cotton)', 'Cashmilon', 'Satin Cotton', 'Wool', 'Georgette', 'Poplin', 'Mixed Vortex', 'Addi Cotton', 'Single Jersey Knit Cotton', 'Denim', 'Sico (Silk & Cotton)', 'Jacquard Cotton', 'Blended Muslin (Muslin+Silk+Endi)'];

export const fabricTypes = ['Cotton', 'Muslin', 'Silk', 'Endi Muslin', 'Mixed Muslin (Muslin & Endi)', 'Soft Silk', 'Half Silk (Silk & Cotton)', 'Endi Silk', 'Mixed Silk (Silk & Cotton)', 'Dupion Silk', 'Katan', 'Mixed Cotton', 'Jamdani Half Silk (Silk & Cotton)', 'Viscott (Viscose & Cotton)', 'Viscose', 'Voile', 'Vortex-Cotton', 'Handloom Cotton', 'Jacquard Viscose', 'Vortex Cotton', 'Mixed Viscose', 'Cottray (Cotton & Rayon)', 'Handloom Viscose', 'Ramie Cotton', 'Mixed Silk', 'Joysree Silk', 'Blended Muslin (Muslin & Silk)', 'Mixed Muslin', 'Endi Silk-Muslin', 'Linen', 'Satin', 'SICO (Silk & Cotton)', 'Cashmilon', 'Satin Cotton', 'Wool', 'Georgette', 'Poplin', 'Mixed Vortex', 'Addi Cotton', 'Single Jersey Knit Cotton', 'Denim', 'Sico (Silk & Cotton)', 'Jacquard Cotton', 'Blended Muslin (Muslin+Silk+Endi)', 'Nakshi Kantha', 'Jamdani', 'Brac Silk', 'Casual', 'Semi-Dressy', 'Exclusive', 'Tops', 'Tunics', 'Dresses', 'Pants', 'Sleepwears', '3-Piece Sets', 'Blouse Pieces', 'Yokes', 'N/A'];

export const wearTypes = ['Saree', 'Shalwar Kameez', 'Maternity', 'Shawls', 'Fabric (Metres)', 'Kurta', 'Panjabi', 'Tops', 'Coats & Jackets', 'Skirts', 'Scarves', 'Nightwear'];

//export const valueAdditions = ['Embroidery', 'Hand Embroidery', 'Screen Print', 'Machine Embroidery', 'Block Print', 'Batik Print', 'Tie & Dye', 'Machine Applique', 'Erri Embroidery', 'Cylinder Dye', 'Hand Applique', 'Exclusive Hand Embroidery', 'Nakshi Kantha Embroidery', 'Acid Dye', 'Hand Paint', 'Digital Print', 'Brush Paint', 'Glass Fitting, Hand Embroidery, Screen Print, Sequin', 'Fountain Dye']
export const valueAdditions = ['embroidery', 'nakshi', 'baluchari', 'handloom', 'lace', 'mirror work', 'sequins', 'stone work', 'tassels', 'fringe', 'applique', 'tangail'];

//export const colors = ['Olive Green', 'Onion Pink', 'White', 'Blue', 'Mustard', 'Pink', 'Stone Blue', 'Multicolour', 'Black', 'Pastel Green', 'Brick Red', 'Fire Orange', 'Yellow Ochre', 'Grey', 'Green', 'Brown', 'Turquoise', 'Dark Olive', 'Orange', 'Peach', 'Sky Blue', 'Blue Grey', 'Seafoam Green', 'Light Green', 'Burgundy', 'Beige', 'Light Lavender', 'Yellow', 'Lavender', 'Lime Green', 'Plum', 'Navy Blue', 'Coral', 'Cider', 'Sage Green', 'Dark Grey', 'Pastel Yellow', 'Strawberry Red', 'Red', 'Maroon', 'Off White', 'Khaki', 'Ivory', 'Olive', 'Burnt Orange', 'Deep Pink', 'Teal', 'Deep Fuchsia', 'Fuchsia', 'Crimson Red', 'Moss Green', 'Lilac', 'Light Khaki', 'Bottle Green', 'Coffee', 'Purple', 'Cyan', 'Deep Peach', 'Light Brown', 'Sienna', 'Dark Teal', 'Pastel Orange', 'Moonlight Blue', 'Watermelon', 'Ecru', 'Hot Pink', 'Twilight Blue', 'Golden', 'Light Peach', 'Honey Mustard', 'Desert Dust', 'Pale Yellow', 'Lemon Yellow', 'Light Mauve', 'Mulberry', 'Sunny Lime', 'Mint Blue', 'Mauve', 'Magenta', 'Light Pink', 'Rust', 'Mint Green', 'Midnight Blue', 'Aqua'];

export const colors = ['yellow', 'orange', 'black', 'purple', 'brown', 'cyan', 'pink', 'blue', 'red', 'white', 'green', 'grey']

export const textures = ['applique', 'buti', 'check', 'dobby', 'tie dye', 'wax dye', 'embroidery', 'floral', 'mauve', 'nakshi', 'opera', 'hand paint', 'painted', 'brush paint', 'printed', 'batik print', 'block print', 'screen print', 'striped', 'textured'];